export const Techstacks = {
  REACT: "React",
  NEXT: "NextJS",
  JAVASCRIPT: "JavaScript",
  TYPESCRIPT: "TypeScript",
  TAILWIND: "Tailwind",
  STYLED_COMPONENTS: "Styled Components",
  GIT: "Git",
  LARAVEL: "Laravel",
  CSS: "CSS",
  HTML: "HTML",
  AIRTABLE: "AirTable",
  UNSPLASH: "Unsplash",
  FRAMER: "Framer",
};
